services:
  db:
    image: mysql:8.0
    container_name: expense_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD:-rootpass}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-expenses_db}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./server/db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 30

  server:
    build: ./server
    container_name: expense_api
    depends_on:
      db:
        condition: service_healthy
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: ${MYSQL_DATABASE:-expenses_tracker}
      MYSQL_USER: ${MYSQL_USER:-expenses_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-rootpass}
      PORT: ${BACKEND_PORT:-8080}
      CORS_ORIGIN: http://localhost:${FRONTEND_PORT:-5173}
    ports:
      - "${BACKEND_PORT:-8080}:8080"
    develop:
      watch:
        - action: sync
          path: ./server
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./server/package.json

  client:
    build:
      context: ./client
      args:
        - VITE_API_URL=${VITE_API_URL:-http://localhost:8080}
    container_name: expense_web
    depends_on:
      - server
    ports:
      - "${FRONTEND_PORT:-5173}:5173"
    environment:
      - VITE_API_URL=${VITE_API_URL:-http://localhost:8080}
    develop:
      watch:
        - action: sync
          path: ./client
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./client/package.json

volumes:
  mysql_data:
